### ISSUE TITLE
Nickname parsing failed when single quotes are used and nickname is at beginning of string

### ISSUE THREAD

**Issue by wseguin** [aeshirey/NameParserSharp#1]
This WILL parse correctly with TREY as the Nickname:
"TREY" ROBERT HENRY BUSH III

This WILL NOT parse correctly:
'TREY' ROBERT HENRY BUSH III
    -- Ends up with First = TREY'    (single quote left in string, probably result of first single quote getting prematurely trimmed)

Note, if the nickname surrounded by single quotes in not at the start of the line, it parses correctly:
ROBERT 'TREY' HENRY BUSH III

**Comment by aeshirey** [comment]
I'm unable to reproduce:

``` C#
[TestMethod]
public void NicknameAtBeginning_DoubleQuote()
{
    var parsed = new HumanName("\"TREY\" ROBERT HENRY BUSH III");

    Assert.AreEqual(parsed.First, "ROBERT");
    Assert.AreEqual(parsed.Middle, "HENRY");
    Assert.AreEqual(parsed.Last, "BUSH");
    Assert.AreEqual(parsed.Nickname, "TREY");
    Assert.AreEqual(parsed.Suffix, "III");
}

[TestMethod]
public void NicknameAtBeginning_SingleQuote()
{
    var parsed = new HumanName("'TREY' ROBERT HENRY BUSH III");

    Assert.AreEqual(parsed.First, "ROBERT");
    Assert.AreEqual(parsed.Middle, "HENRY");
    Assert.AreEqual(parsed.Last, "BUSH");
    Assert.AreEqual(parsed.Nickname, "TREY");
    Assert.AreEqual(parsed.Suffix, "III");
}
```

![double-quote](https://cloud.githubusercontent.com/assets/1210458/11162082/3d064146-8a46-11e5-956e-f669fc57fd21.png)
![single-quote](https://cloud.githubusercontent.com/assets/1210458/11162083/3d06893a-8a46-11e5-940b-ba9cc86cbab9.png)

Can you confirm that your input strings are exactly as described?

**Comment by wseguin** [comment]
My fault entirely. Rather embarrassing. String modified downstream (first single quote being dropped). Sorry about that.
