### ISSUE TITLE
Request functionality to add to lists.

### ISSUE THREAD

**Issue by TCavanaugh** [aeshirey/NameParserSharp#18]
Love the functionality of this utility.  

Our data contains some slightly different variants of some of the suffixes. e.g. "2nd" or "3rd" instead of "Jr", "II", or "III".  Rather than needing to try to anticipate every way that users will enter their suffixes, etc. It might be nice to allow the consuming developer to add their own tweaks when their data presents them.

**Comment by aeshirey** [comment]
This should be really straightforward. Suffixes, for example, are just [a static HashSet](https://github.com/aeshirey/NameParserSharp/blob/2b1509a7abaf98fecdf637e991bd083166d85c32/NameParser/NameParser/Config.cs#L47). This, along with prefixes, titles, etc., could be made public or given public methods to add new values.

**Comment by aeshirey** [comment]
With apologies for the very long delay, I'm making the internal lists public so you can modify them. An example of the currently incorrect behavior and the correct behavior when adding a new suffix:

```csharp
public void AddToLists()
{
    var as_is = new HumanName("Mr. John Smith 2nd");
    Assert.AreEqual("Mr.", as_is.Title);
    Assert.AreEqual("John", as_is.First);
    Assert.AreEqual("Smith", as_is.Middle);
    Assert.AreEqual("2nd", as_is.Last);
    Assert.AreEqual("", as_is.Suffix);

    HumanName.Suffixes.Add("2nd");
    var with_2nd = new HumanName("Mr. John Smith 2nd");
    Assert.AreEqual("Mr.", with_2nd.Title);
    Assert.AreEqual("John", with_2nd.First);
    Assert.AreEqual("Smith", with_2nd.Last);
    Assert.AreEqual("2nd", with_2nd.Suffix);
}
```

Note that this change is _strictly_ allowing new values to be added. If you try parsing something like "Mr. John Smith the 2nd", the word "the" throws off parsing.

**Comment by aeshirey** [comment]
The new version is [available on nuget](https://www.nuget.org/packages/NameParserSharp/1.5.0). You should be able to install with `Install-Package NameParserSharp -Version 1.5.0`
