### ISSUE TITLE
Req: Seperate prefixes

### ISSUE THREAD

**Issue by Toxaris-NL** [aeshirey/NameParserSharp#2]
This is not so much an issue as a request for a feature. I would like to have the prefixes separately from the last name. At the moment they are joined with the lastname in the function 'join_on_conjunctions'.

The reason is for sorting. For example, my own name is Sander van der Linden. Although my lastname is 'van der Linden', it is sorted under the l, not the v. That is not uncommon in European countries at least. If the prefixes are separated, this can be done much more easily. From what I gather, the following changes would be required. It seems to work, but you might need to check with more testcases...:

In the property FullName (around line 39/40) add `_NicknameList = new List<string>();`
Add around 74: 

```
public string Prefix
        {
            get { return string.Join(" ", _PrefixList); }
        }
```

Around line 84:
`private IList<string> _PrefixList;`

Around line 138: 

```
if (includeEmpty || !string.IsNullOrEmpty(Prefix))
                d["prefix"] = Prefix;
```

Around line 166:

```
private static bool ArePrefixes(string piece)
{
    return IsPrefix(piece.Split(" ").First); 'check only if the first is a prefix if there are more.
}
```

Around line 272:

```
else if (ArePrefixes(piece))
                        _PrefixList.Add(piece)
```

line 517 should become (since there can be multiple prefixes, even if there is a suffix:
 `var newPiece = string.Join(" ", pieces.Skip(i + prefixes.Length).Take(j - i + 1));`

line 521: `.Concat({ string.Join(" ", prefixes) })`
line 522: `.Concat({ newPiece })`
line 527-529 :

```
pieces = pieces.Take(i).ToList()
.Concat({ string.Join(" ", prefixes) })
.Concat({ string.Join(" ", pieces.Skip(i + prefixes.Length).ToList()) }).ToList
```

**Comment by aeshirey** [comment]
I wonder if this might be more elegantly solved by post-parsing the last name according to the prefixes? Or, if the goal is to be able to better sort, maybe a simple public property that filters out last name prefixes that can be used for LINQ sorting. For example:

``` c#
public string RawSurname
  {
    get
    {
        return string.Join(" ", _LastList
            .SelectMany(part => part.Split(' '))
            .SkipWhile(part => Prefixes.Contains(part)));
    }
}
```

This would give you the ability to do the following:

``` c#
[TestMethod]
public void RawSurname()
{
    var parsed = new HumanName("John Smith");
    Assert.AreEqual(parsed.RawSurname, "Smith");

    parsed = new HumanName("Johannes van der Waals");
    Assert.AreEqual(parsed.RawSurname, "Waals");
}
```

And therefore, do something as follows:

``` c#
var people = new [] { "John X", "Johannes van der Waals", "Juan de Zapata" };
var parsed = people
    .Select(person => new HumanName(person))
    .OrderBy(person => person.RawSurname)
    .Select(person => string.Format("{0}, {1}", person.Last, person.First);

// parsed:
// van der Waals, Johannes
// X, John
// de Zapata, Juan
```

**Comment by Toxaris-NL** [comment]
While that would seem to sort the sorting issue partially, it would not be a complete solution. The display would also be different (Waals, Johannes van der). Also, if the 'RawSurname' is the same, the sorting will use the prefixes to determine the sequence. So, 'Linden, van der' comes after 'Linden, van den'.
The routine you mentioned can be used as a base for that of course, but if the prefixes would be a seperate attribute, it would be a lot easier. In databases they are also stored in a different field or as 'Linden, van der'. It would make processing names easier.

I do understand the reluctance though of implementing this.

**Comment by aeshirey** [comment]
[According to Wikipedia](https://en.wikipedia.org/wiki/Van_%28Dutch%29):

> In the Netherlands, and Suriname, names starting with "van" are filed under the initial letter of the following name proper, so Johannes van der Waals is filed under "W", as: `Waals, Johannes van der` or `van der Waals, Johannes`

You've got better cultural context than I do, but this is basically what I have to inform myself. So I think the biggest question with regard to this change is whether this library should presume anything about displaying the name or whether it should just separate out last name prefixes from the base last name. I'm inclined to think the latter and leave formatting to the caller. For example:

``` c#
var person = new HumanName("Johannes van der Waals");
Assert.AreEqual("Johannes", person.First);
Assert.AreEqual("van der", person.LastPrefixes); // specifically, the prefixes to the last name
Assert.AreEqual("Waals", person.LastBase); // only the base component of the last name
Assert.AreEqual("van der Waals", person.Last); // the full last name, combined
```

This means you can still easily sort by the base name but further discriminate based on the prefixes:

``` c#
IEnumerable<HumanName> people = getPeople();
var sorted = people
   .OrderBy(person => person.LastBase)
   .ThenBy(person => person.LastPrefixes);
```

Yet you can also format according to your own needs:

``` c#
Console.WriteLine("{0}, {1} {2}", person.LastBase, person.First, person.LastPrefixes); // "Waals, Johannes van der"
Console.WriteLine("{0}, {1}", person.Last, person.First); // "van der Waals, Johannes"
```

**Comment by Toxaris-NL** [comment]
Hmm, perhaps in Suriname, but Wikipedia is wrong about the Netherlands for sure. What you propose will work I guess. In that way, the prefixes can be separated from the lastname if you want, but not be obliged to.

**Comment by aeshirey** [comment]
Pushed new code with unit tests. The [NuGet Package](https://www.nuget.org/packages/NameParserSharp/1.1.0) has been updated to include this code as well.
