### ISSUE TITLE
Improvement: A few examples that aren't parsing properly

### ISSUE THREAD

**Issue by rebeccapowell** [aeshirey/NameParserSharp#4]
First of all, this is an excellent library and in most of our use cases it is working really well.

I have a number of edge case examples where it isn't parsing correctly, namely those with joint names:

N.B. output is string.Format (Title, First, Last)
- Mr S Bloggs and Miss L Jones => Mr S Jones 
- Mrs K Bloggs and Mr S Jones => Mrs K Jones
- Mr R & Mrs J Bloggs => Mr R Bloggs
- Mr Ian Bloggs &  Mrs Elizabeth Bloggs => Mr Ian Bloggs
- Mrs M  L  Jones => Mrs L Jones

Probably edge cases, but I'd thought I'd drop you a note.

**Comment by aeshirey** [comment]
I've got a proposed enhancement that adds an `AdditionalName` property to HumanName. It should handle several of the input cases you bring up. Here's an example:

```
[TestMethod]
public void TwoNames_MacAthur()
{
    HumanName.ParseMultipleNames = true;
    var parsed = new HumanName("John D. and Catherine T. MacArthur");

    Assert.AreEqual("John", parsed.First);
    Assert.AreEqual("D.", parsed.Middle);
    Assert.AreEqual("MacArthur", parsed.Last);

    Assert.IsNotNull(parsed.AdditionalName);

    Assert.AreEqual("Catherine", parsed.AdditionalName.First);
    Assert.AreEqual("T.", parsed.AdditionalName.Middle);
    Assert.AreEqual("MacArthur", parsed.AdditionalName.Last);

    Assert.IsNull(parsed.AdditionalName.AdditionalName);
}
```

The change will allow multiple name parsing by setting `HumanName.ParseMultipleNames = true`; by default, it will be turned off. No other changes to callers would be required (except to be able to read multiple names. And it would even be able to handle a string of names (eg, "Mr John Smith and Mrs Jane Doe and President Abraham Lincoln").

**Comment by aeshirey** [comment]
I've updated the Nuget Package to include the new code functionality. [NameParserSharp 1.2.0](https://www.nuget.org/packages/NameParserSharp/1.2.0) is now available.
