### ISSUE TITLE
NuGet DLL version is incorrect

### ISSUE THREAD

**Issue by rebeccapowell** [aeshirey/NameParserSharp#6]
I've just upgraded to 1.2.0.0 (thanks for the updates btw). I've got a build running in TeamCity for my project that is using NameParserSharp, and I am using NuGet Package restore. I noticed that your DLLs have the wrong version number. Shouldn't it match the release number?

![image](https://cloud.githubusercontent.com/assets/586841/16373971/c213395a-3c54-11e6-9849-ab18cde8946e.png)

Not a major issue, but it looks a little odd, because the version number never increases between releases. It could cause users DLL version issues as well.

If you have an automated build process using TeamCity or Maven, you can patch the assembly version automatically as part of the automated build process: https://essenceofcode.com/2013/09/18/assembly-versioning-with-team-city-and-git/

**Comment by aeshirey** [comment]
You're correct; the DLL should match the version. I just never bothered to set it in Visual Studio. I will address this in the next version.

**Comment by aeshirey** [comment]
Finally updated the version in the DLL, which also fixes issues #8 and #9. The new DLL is [on nuget.org here](https://www.nuget.org/packages/NameParserSharp/1.3.0).
