### ISSUE TITLE
Incorrectly identifying name parts

### ISSUE THREAD

**Issue by GHosaPhat** [aeshirey/NameParserSharp#9]
I was trying to develop a name parsing routine myself when I came across this repo, and I think it will be tremendously helpful for my use case.  However, I've run across a couple of instances that seem to be tripping the parser up a bit.

The first one is how the parser handles names that actually include one of the pre-defined titles as a part of the name.  For example, the name "Robert Lee Elder III" does not parse correctly.  In this case, it should be:

**First Name:** Robert
**Middle Name:** Lee
**Last Name:** Elder
**Suffix:** III

However, what I actually get is:

<span style="color:red">**_Title:_** Elder</span>
**First Name:** Robert
**Middle Name:** Lee
<span style="color:red">**_Last Name:_** III</span>

Obviously, I can simply remove this entry from the list of titles and recompile for my purposes today, but it would be better if it's possible to rework the logic to ignore the title if it's determined that the original name is in **First [Middle] Last** format and the "title" is found at or towards the end.  I realize that logic can get extremely complicated - that's the main reason I was trying to find someone else's code to handle it for me - but it would make this much more reliable.

The second is, I realize, not something that the parser is currently designed to handle: business names.  Because of my needs, I've got some additional tests that seem to be handling that, but it might be something you consider adding in a future push.  This would involve identifying the abbreviations and such for businesses (LLC, Corp, Assn, etc.).

**Comment by GHosaPhat** [comment]
Just to follow up regarding my testing.  The name specified above ("Robert Lee Elder III") will parse correctly IF there is a comma ahead of the generational suffix.  Without the comma, it doesn't appear to catch it correctly.

**Comment by aeshirey** [comment]
Ack. I haven't had time to look into this lately, but I'll try to look into it.

**Comment by aeshirey** [comment]
The cause of the issue reported is that the input "Robert Lee Elder III" conflicts with the hard-coded list of suffixes. The library was assuming that both "Elder" and "III" were suffixes.

I've updated it to try to better understand this scenario. Importantly, the change didn't break existing unit tests, though I can't guarantee other users' use cases aren't adversely affected.

Regarding the other point of doing organization name parsing - this would probably be a good additional class to add to the library but will have to wait until I have more time.
